//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneTrainer.Mobile.Application.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DroneTrainer.Mobile.Application.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновити.
        /// </summary>
        public static string HomeRefreshButton {
            get {
                return ResourceManager.GetString("HomeRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої сесії.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть пароль.
        /// </summary>
        public static string LoginPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        public static string LoginSignInButton {
            get {
                return ResourceManager.GetString("LoginSignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вітаємо в DroneTrainer!.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ім&apos;я користувача.
        /// </summary>
        public static string LoginUserNamePlaceholder {
            get {
                return ResourceManager.GetString("LoginUserNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        public static string LogOutButton {
            get {
                return ResourceManager.GetString("LogOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершити спробу.
        /// </summary>
        public static string SessionEndAttempt {
            get {
                return ResourceManager.GetString("SessionEndAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершити сесію.
        /// </summary>
        public static string SessionEndSession {
            get {
                return ResourceManager.GetString("SessionEndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Час проходження сесії.
        /// </summary>
        public static string SessionSessionCompletionTime {
            get {
                return ResourceManager.GetString("SessionSessionCompletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розпочати спробу.
        /// </summary>
        public static string SessionStartAttempt {
            get {
                return ResourceManager.GetString("SessionStartAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розпочати сесію.
        /// </summary>
        public static string SessionStartSession {
            get {
                return ResourceManager.GetString("SessionStartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент успішно пройдених етапів.
        /// </summary>
        public static string SessionSuccessfullGatesPercent {
            get {
                return ResourceManager.GetString("SessionSuccessfullGatesPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деталі сесії.
        /// </summary>
        public static string SessionTitle {
            get {
                return ResourceManager.GetString("SessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент неуспішно пройдених етапів.
        /// </summary>
        public static string SessionUnsuccessfullGatesPercent {
            get {
                return ResourceManager.GetString("SessionUnsuccessfullGatesPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коєфіцієнт успішності.
        /// </summary>
        public static string SessionUserSuccessCoeficient {
            get {
                return ResourceManager.GetString("SessionUserSuccessCoeficient", resourceCulture);
            }
        }
    }
}
